encoding: UTF-8
markdown: redcarpet
highlighter: false 
permalink: /:month-:day-:year/:title.html

url:

redcarpet:
  extensions: ["fenced_code_blocks", "highlight", "strikethrough"]
  render_options:
timezone: Asia/Shanghai
excerpt_separator: ""
paginate: 10

gems: [jekyll-paginate]