encoding: UTF-8
markdown: kramdown
highlighter: pygments 
permalink: /:month-:day-:year/:title.html

url:

kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil
timezone: Asia/Shanghai
excerpt_separator: ""
paginate: 10

gems: [jekyll-paginate]