name: "cyningsun"
meta_description: 微信后台开发，
encoding: UTF-8
markdown: kramdown
permalink: /:month-:day-:year/:title.html

url:https://cyningsun.github.io

kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil
timezone: Asia/Shanghai
excerpt_separator: ""
paginate: 10

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
