name: 有疑者说
author: cyningsun
encoding: UTF-8
markdown: kramdown
permalink: /:month-:day-:year/:title.html
description: 博学、慎思、明辨、笃行
weibo: http://weibo.com/CyningSun
gmail: mailto:sunyinhangscut@gmail.com
douban: https://www.douban.com/people/cyningscut
github: https://github.com/cyningsun

kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  syntax_highlighter: rouge
timezone: Asia/Shanghai
excerpt_separator: ""
paginate: 10

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap


defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
